### ISSUE TITLE
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

### ISSUE THREAD

**Issue by trinh-hoang-hiep** [Lornatang/CycleGAN-PyTorch#6]
i met this error
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    for i, data in progress_bar:
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hoang/Desktop/luanvan/cycleGAN/CycleGAN-PyTorch/cyclegan_pytorch/datasets.py", line 38, in __getitem__
    item_B = self.transform(Image.open(self.files_B[random.randint(0, len(self.files_B) - 1)]))
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 226, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 351, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

**Comment by Lornatang** [comment]
From error analysis, are there non-RGB images in your dataset?

**Comment by trinh-hoang-hiep** [comment]
> From error analysis, are there non-RGB images in your dataset? 
i just run only on horse2zebra dataset
i downgraded torchvision to 0.2.1 and it fixed this issue for me. ,i downgraded torch to 1.0.1
but i met new issue

Namespace(batch_size=1, cuda=False, dataroot='./data', dataset='horse2zebra', decay_epochs=2, epochs=4, image_size=256, lr=0.0002, manualSeed=None, netD_A='', netD_B='', netG_A2B='', netG_B2A='', outf='./outputs', print_freq=100)
Random Seed:  6298
[0/3][16/1333] Loss_D: 0.0558 Loss_G: 10.8878 Loss_G_identity: 3.1222 loss_G_GAN: 1.8621 loss_G_cycle: 5.9035:   1%|▋                                                  | 17/1334 [04:17<5:32:23, 15.14s/it]
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    identity_image_B = netG_A2B(real_image_B)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hoang/Desktop/luanvan/cycleGAN/CycleGAN-PyTorch/cyclegan_pytorch/models.py", line 93, in forward
    return self.main(x)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hoang/anaconda3/envs/cyclegan/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 1, 262, 262] to have 3 channels, but got 1 channels instead
