### ISSUE TITLE
A question about data type

### ISSUE THREAD

**Issue by pierowu** [Lornatang/CycleGAN-PyTorch#8]
I just run train.py without changing. The error report shows information below.
Traceback (most recent call last):
  File "D:/research/noofficial_cyclegan/cyclegan-pytorch-master/train.py", line 32, in <module>
    from dataset import CUDAPrefetcher, ImageDataset
  File "D:\research\noofficial_cyclegan\cyclegan-pytorch-master\dataset.py", line 25, in <module>
    from imgproc import image_to_tensor, random_rotate, random_horizontally_flip, random_vertically_flip
  File "D:\research\noofficial_cyclegan\cyclegan-pytorch-master\imgproc.py", line 150, in <module>
    center: tuple[int, int] = None,
TypeError: 'type' object is not subscriptable

Is my python version wrong? Thank you for answering.

**Comment by pierowu** [comment]
I already solve this problem by updating python to 3.10

**Comment by Lornatang** [comment]
Fixed.
